# Generated by Django 4.0.1 on 2022-01-12 21:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=255, verbose_name='Autorzy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(13)], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=255, verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(verbose_name='Ilość stron'),
        ),
        migrations.AlterField(
            model_name='book',
            name='previewLink',
            field=models.URLField(verbose_name='Odnośnik do okładki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(verbose_name='Data publikacji'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
    ]
