# Generated by Django 4.0.1 on 2022-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=100, null=True, verbose_name='Wpisz słowo kluczowe'),
        ),
    ]
