# Generated by Django 4.0.1 on 2022-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_keyword_keywords_keyword_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=255, verbose_name='ISBN'),
        ),
    ]
