# Generated by Django 4.0.1 on 2022-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(null=True, verbose_name='Ilość stron'),
        ),
    ]
