# Generated by Django 4.0.1 on 2022-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_pagecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='previewLink',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=255, null=True, verbose_name='Odnośnik do okładki'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=255, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.CharField(max_length=255, null=True, verbose_name='Ilość stron'),
        ),
    ]
