# Generated by Django 4.0.1 on 2022-01-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_authors_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(blank=True, verbose_name='Data publikacji'),
        ),
    ]
