# Generated by Django 4.0.1 on 2022-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data publikacji'),
        ),
    ]
